"""Dynamic compression filter — wraps a CompressionRule as a BaseFilter for SafeOutputFilter.

This is the bridge between the self-evo rule system and the existing filter chain.
Each CompressionRule gets wrapped in a DynamicCompressionFilter instance and injected
via SafeOutputFilter.add_filter().
"""

import logging
import re

from ..output_filter import BaseFilter, FilterContext
from .models import CompressionRule

logger = logging.getLogger(__name__)


class DynamicCompressionFilter(BaseFilter):
    """Applies a single CompressionRule within the SafeOutputFilter chain.

    Lifecycle:
    1. Created from a CompressionRule (generated by Planner or Evolver)
    2. Injected into SafeOutputFilter via add_filter()
    3. Automatically runs during _smart_compress() → SafeOutputFilter.process()
    4. Self-disables when rule.confidence drops below threshold
    5. Tracks rule.times_applied for cache persistence
    """

    CONFIDENCE_THRESHOLD = 0.3  # Below this, rule auto-disables

    def __init__(self, rule: CompressionRule):
        super().__init__()
        self.name = f"dynamic_{rule.rule_id}"
        self.priority = rule.priority
        self.rule = rule

        # Pre-compile regexes for performance (with error handling for bad LLM-generated patterns)
        self._trigger: re.Pattern | None = self._safe_compile(rule.trigger_regex)
        self._keeps: list[re.Pattern] = [
            p
            for p in (self._safe_compile(pat) for pat in rule.keep_patterns)
            if p is not None
        ]
        self._strips: list[re.Pattern] = [
            p
            for p in (self._safe_compile(pat) for pat in rule.strip_patterns)
            if p is not None
        ]

    @staticmethod
    def _safe_compile(pattern: str) -> re.Pattern | None:
        """Compile regex with error handling for LLM-generated patterns."""
        try:
            return re.compile(pattern, re.IGNORECASE)
        except re.error as e:
            logger.warning(f"Invalid regex pattern '{pattern}': {e}")
            return None

    def should_skip(self, context: FilterContext) -> bool:
        """Skip if: no trigger compiled, confidence too low, command doesn't match, or has error."""
        if self._trigger is None:
            return True
        if self.rule.confidence < self.CONFIDENCE_THRESHOLD:
            return True
        if not context.command:
            return True
        if context.has_error:
            return True  # Never compress error output
        return not self._trigger.search(context.command)

    def filter(self, text: str, context: FilterContext) -> str:
        """Apply keep/strip pattern filtering with head/tail preservation."""
        lines = text.split("\n")
        total = len(lines)
        min_lines = self.rule.keep_first_n + self.rule.keep_last_n + 5

        # Too short to compress — not worth the risk of losing info
        if total <= min_lines:
            return text

        # Split into head / body / tail
        head = lines[: self.rule.keep_first_n]
        tail_start = (
            total - self.rule.keep_last_n if self.rule.keep_last_n > 0 else total
        )
        tail = lines[tail_start:] if self.rule.keep_last_n > 0 else []
        body = lines[self.rule.keep_first_n : tail_start]

        # Filter body lines
        filtered_body: list[str] = []
        stripped_count = 0

        for line in body:
            # Priority 1: Keep if matches any keep_pattern
            if any(pattern.search(line) for pattern in self._keeps):
                filtered_body.append(line)
                continue

            # Priority 2: Strip if matches any strip_pattern
            if any(pattern.search(line) for pattern in self._strips):
                stripped_count += 1
                continue

            # Default: keep (conservative — better to over-preserve than lose info)
            filtered_body.append(line)

        # Apply max_lines cap on body
        if self.rule.max_lines is not None and len(filtered_body) > self.rule.max_lines:
            stripped_count += len(filtered_body) - self.rule.max_lines
            filtered_body = filtered_body[: self.rule.max_lines]

        # Assemble result
        result_lines: list[str] = list(head)
        if stripped_count > 0 and self.rule.summary_header:
            result_lines.append(
                f"{self.rule.summary_header} [{stripped_count} lines removed]"
            )
        result_lines.extend(filtered_body)
        result_lines.extend(tail)

        self.rule.times_applied += 1
        return "\n".join(result_lines)
