"""Data models for the self-evolving terminal output compression system."""

from pydantic import BaseModel, Field


class CompressionRule(BaseModel):
    """A single terminal output compression rule.

    Each rule targets a specific command type (via trigger_regex) and defines
    which output lines to keep vs strip. Rules are generated by LLM at task start,
    evolve during execution via feedback, and persist across tasks in cache.
    """

    rule_id: str  # Unique identifier, e.g. "pip_install_compress"
    trigger_regex: str  # Regex to match against command string
    description: str = ""  # Human-readable description (stored in cache)
    keep_patterns: list[str] = Field(
        default_factory=list
    )  # Regex: lines matching these are ALWAYS kept
    strip_patterns: list[str] = Field(
        default_factory=list
    )  # Regex: lines matching these are removed
    keep_first_n: int = 5  # Always keep first N lines of output
    keep_last_n: int = 10  # Always keep last N lines of output
    max_lines: int | None = None  # Cap on body lines after filtering (None = no cap)
    summary_header: str | None = None  # Prepend this when compression occurs
    priority: int = 42  # Position in SafeOutputFilter chain (30-65 range)

    # Evolution tracking — updated at runtime, persisted across tasks
    confidence: float = 1.0  # 1.0 = fully trusted, <0.3 = auto-disabled, 0.0 = frozen
    times_applied: int = 0  # How many times this rule actually fired
    times_complained: int = 0  # How many times agent complained about this rule


class CompressionPlan(BaseModel):
    """The compression plan for a single task, produced by the Planner.

    Contains three categories of rules:
    - selected: existing cached rules chosen as-is
    - modified: cached rules that were adjusted for this task
    - new: freshly generated rules for this task
    """

    task_category: str
    selected_rule_ids: list[str] = Field(default_factory=list)
    modified_rules: list[CompressionRule] = Field(default_factory=list)
    new_rules: list[CompressionRule] = Field(default_factory=list)

    def all_active_rules(self) -> list[CompressionRule]:
        """Return all rules that should be injected into the filter chain."""
        return self.modified_rules + self.new_rules


class FeedbackSignal(BaseModel):
    """A detected feedback event indicating compression quality issues.

    Created by FeedbackCollector when the agent shows signs of dissatisfaction
    with compressed output. Used by RuleEvolver to spawn replacement rules.
    """

    episode: int
    signal_type: str  # "complaint" | "uncovered_big_output"
    command: str  # The command whose output triggered the signal
    rules_applied: list[str]  # rule_ids that fired on the problematic output
    raw_output_length: int
    compressed_output_length: int
    signal_source: str = ""  # explicit_feedback | analysis_heuristic | retry_command_heuristic
    signal_details: str = ""  # Short explanation for why the signal fired
    agent_response_snippet: str = ""  # What the agent said (for spawn prompt context)
    raw_output_snippet: str = ""  # Original output snippet (for spawn prompt context)
